name: build check

on:
  pull_request:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Pull submodule latest commit
        run: |
          git submodule foreach git pull --ff origin production

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Generate data.json
        run: python tool/convert/convert_csv_to_json.py
        env:
          TZ: 'Asia/Tokyo'   

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile
      - run: yarn run test
      - run: yarn run generate:deploy --fail-on-page-error

      - name: archive dist
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
